Repository Miso-Code/misw4203-moviles-2023, pull requests merged in 2023-04, with the labels that each got.

#13 feat: added menu layout with routes to ease further user stories
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/misw4203_moviles_2023/ui/view/MainActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/active_menu_item.xml
  app/src/main/res/drawable/ic_album.xml
  app/src/main/res/drawable/ic_artist.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_my_collections.xml
  app/src/main/res/drawable/ic_user_circle.xml
  app/src/main/res/drawable/ic_user_color.xml
  app/src/main/res/drawable/ic_users.xml
  app/src/main/res/drawable/side_nav_bar.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/app_bar_navigation_drawer.xml
  app/src/main/res/layout/content_navigation_drawer.xml
  app/src/main/res/layout/nav_header_navigation_drawer.xml
  app/src/main/res/menu/activity_navigation_drawer_drawer.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-hdpi/user_icon.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#18 Feature/hu02 consultar la información detallada album
  app/lint-config.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/misw4203moviles2023/adapter/TrackAdapter.kt
  app/src/main/java/com/example/misw4203moviles2023/data/AlbumRepository.kt
  app/src/main/java/com/example/misw4203moviles2023/data/model/AlbumModel.kt
  app/src/main/java/com/example/misw4203moviles2023/data/model/TrackModel.kt
  app/src/main/java/com/example/misw4203moviles2023/data/network/AlbumApiClient.kt
  app/src/main/java/com/example/misw4203moviles2023/data/network/AlbumService.kt
  app/src/main/java/com/example/misw4203moviles2023/domain/album/GetAlbumById.kt
  app/src/main/java/com/example/misw4203moviles2023/ui/view/AlbumDetail.kt
  app/src/main/java/com/example/misw4203moviles2023/ui/view/AlbumList.kt
  app/src/main/java/com/example/misw4203moviles2023/ui/view/MainActivity.kt
  app/src/main/java/com/example/misw4203moviles2023/ui/viewModel/AlbumDetailViewModel.kt
  app/src/main/java/com/example/misw4203moviles2023/ui/viewModel/AlbumListViewModel.kt
  app/src/main/res/drawable/ic_track.xml
  app/src/main/res/layout/app_bar_navigation_drawer.xml
  app/src/main/res/layout/fragment_album_detail.xml
  app/src/main/res/layout/track_row.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  scripts/pre-commit
Labels: enhancement

#19 Update GitHub Actions for release/build
  .github/workflows/build-and-test.yml
  .github/workflows/create-release.yml
  .gitignore
  app/build.gradle
Labels: feature

#22 [MINOR] fix: correction size and scroll y detail album (#21)
  app/src/main/res/layout/fragment_album_detail.xml
  app/src/main/res/values/dimens.xml
Labels: bugfix
